# Generated by Django 5.2.7 on 2025-11-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(help_text='Enter course code (e.g., IS424)', max_length=50)),
                ('title', models.CharField(help_text='Enter a descriptive title for your note', max_length=100)),
                ('content', models.TextField(help_text='Enter your note content here', max_length=10000)),
                ('date', models.DateField(auto_now_add=True, help_text='Date will be automatically set')),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('complete', 'Complete')], default='ongoing', max_length=20)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
