# Generated by Django 5.2.8 on 2025-11-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_delete_coursenote'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'On going')], default='ongoing', max_length=20),
        ),
    ]
